---
- name: Add official Nginx repo
  apt_repository:
    repo: 'ppa:nginx/stable'
    update_cache: yes

- name: install NGINX Server.
  apt: pkg=nginx-full state=present

- name: make sure ssl directory exists
  file: path={{ ssl_cert_dir }} state=directory

- import_tasks: htpasswd.yml

- name: copy base nginx configuration.
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify: reload nginx

- name: delete default vhost.
  action: file path=/etc/nginx/sites-enabled/default state=absent
  notify: reload nginx

- name: copy site host port 80 configuration.
  template: src=site.80.conf.j2 dest=/etc/nginx/sites-available/{{ nginx_conf_file_name }}.80.conf
  notify: reload nginx

- name: put host port 80 configuration in sites-enabled
  file: src=/etc/nginx/sites-available/{{ nginx_conf_file_name }}.80.conf dest=/etc/nginx/sites-enabled/{{ nginx_conf_file_name }}.80 state=link
  notify: reload nginx

- name: ensure nginx is running
  service: name=nginx state=started
