---
    #= Dev
#===================================================
- hosts: dev
  vars_files:
    - vars.yml
  gather_facts: false
  become: true
  become_method: sudo

  roles:
    - common
    - nginx
    - nodejs
    - project_data

#= Production
#===================================================
- hosts: production
  vars_files:
    - vars.yml
  gather_facts: false
  become: true
  become_method: sudo

  roles:
    - common
    - nginx
    - nodejs
    - project_data
